venues = [
  {
    name: "Bar do Cuscuz",
    slug: "bar-do-cuscuz",
    category: "bar",
    address: "Av. Cabo Branco, 3056",
    neighborhood: "Cabo Branco",
    city: "João Pessoa",
    state: "PB",
    latitude: -7.1265,
    longitude: -34.8235,
    is_partner: true,
    partner_tier: "gold_partner",
    cover_image_url: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800",
    logo_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200",
    description: "O point mais famoso e vibrante da orla de João Pessoa! Gastronomia regional autêntica, chopp trincando, música ao vivo e o melhor clima para paquerar e fazer amigos.",
    instagram: "@bardocuscuzjp",
    phone: "(83) 3247-2020",
    perk_title: "🍹 Caipirinha ou Chopp de Boas-Vindas",
    perk_description: "Apresente o aplicativo Azarar VIP para o garçom e ganhe 1 Drink cortesia na compra de qualquer petisco!",
    opening_hours: "Terça a Domingo · 16h às 02h",
    vibe: "🔥 Forró, Sertanejo & Azaração na Orla",
    checkins_count: 28,
    verified_at: Time.current
  },
  {
    name: "Dona Branca Bar & Restaurante",
    slug: "dona-branca",
    category: "bar",
    address: "Av. Gov. Flávio Ribeiro Coutinho, 115",
    neighborhood: "Manaíra",
    city: "João Pessoa",
    state: "PB",
    latitude: -7.0980,
    longitude: -34.8380,
    is_partner: false,
    partner_tier: "organic",
    cover_image_url: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800",
    logo_url: "",
    description: "Bar tradicional com excelente culinária regional, cerveja gelada e mesinhas na calçada.",
    instagram: "@donabrancajp",
    phone: "(83) 3246-1212",
    perk_title: "",
    perk_description: "",
    opening_hours: "Quarta a Domingo · 17h às 01h",
    vibe: "🍻 Cerveja gelada, petiscos & bate-papo",
    checkins_count: 14
  },
  {
    name: "Orla de Cabo Branco",
    slug: "orla-cabo-branco",
    category: "beach",
    address: "Av. Cabo Branco (Calçadão)",
    neighborhood: "Cabo Branco",
    city: "João Pessoa",
    state: "PB",
    latitude: -7.1350,
    longitude: -34.8210,
    is_partner: false,
    partner_tier: "organic",
    cover_image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    logo_url: "",
    description: "O point ao ar livre de quem ama praia, caminhada no fim de tarde, água de coco e paquera na brisa do mar.",
    instagram: "",
    phone: "",
    perk_title: "",
    perk_description: "",
    opening_hours: "Aberto 24 horas · Movimento 16h às 23h",
    vibe: "🏖️ Brisa do mar, caminhada & drinks praianos",
    checkins_count: 19
  },
  {
    name: "Posto Select (Beira Rio)",
    slug: "posto-select-beira-rio",
    category: "convenience",
    address: "Av. Min. José Américo de Almeida, 1200",
    neighborhood: "Torre",
    city: "João Pessoa",
    state: "PB",
    latitude: -7.1220,
    longitude: -34.8510,
    is_partner: false,
    partner_tier: "organic",
    cover_image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    logo_url: "",
    description: "Famoso esquenta pré-balada com conveniência aberta, som ambiente e encontro de galera nos fins de semana.",
    instagram: "",
    phone: "",
    perk_title: "",
    perk_description: "",
    opening_hours: "Aberto 24 Horas",
    vibe: "⚡ Esquenta pré-balada, cerveja & resenha",
    checkins_count: 11
  },
  {
    name: "Feirinha de Tambaú",
    slug: "feirinha-de-tambau",
    category: "beach",
    address: "Praça Santo Antônio, Av. Alm. Tamandaré",
    neighborhood: "Tambaú",
    city: "João Pessoa",
    state: "PB",
    latitude: -7.1180,
    longitude: -34.8270,
    is_partner: false,
    partner_tier: "organic",
    cover_image_url: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=800",
    logo_url: "",
    description: "Coração cultural e turístico de Tambaú. Tapiocas, artesanato, música ao vivo e fluxo constante de turistas e locais.",
    instagram: "",
    phone: "",
    perk_title: "",
    perk_description: "",
    opening_hours: "Todos os dias · 17h às 23h",
    vibe: "🥥 Ponto de encontro, tapioca & paquera turística",
    checkins_count: 16
  }
]

venues.each do |attrs|
  venue = Venue.find_or_initialize_by(slug: attrs[:slug])
  venue.update!(attrs)
  puts "Venue #{venue.name} saved!"
end
